# mkusbrom.py — turn vendor/usb_hid_host_rom.hex into src/usb_hid_rom.svh.
#
#   python tools/mkusbrom.py
#
# WHY THIS EXISTS, AND WHY THE UPSTREAM ROM MODULE IS NOT VENDORED.
#
# The core's own ROM wrapper does:
#
#     initial $readmemh("usb_hid_host_rom.hex", mem);
#
# — a RELATIVE path, resolved against whatever directory the tool happens to run
# in. koti runs its simulators from `test/` (cocotb, the Makefile) and yosys
# from the repo root, so no single relative path is right for both. And the
# failure is SILENT: a $readmemh that cannot open its file is a warning, not an
# error, so the ROM fills with x, the USB core's microcode never runs, and the
# symptom on the bench is a keyboard that simply never enumerates — with a green
# build and no message anyone would look at twice.
#
# This repo already hit that class of problem and already solved it: `font_rom`
# is an `include` pulled in by vga_text.sv, and BOTH builders pass `-I src`, so
# the path resolves identically everywhere. This does the same for the USB
# microcode. The .hex stays vendored verbatim as DATA; only the wrapper is
# koti's, and src/usb_hid_host_rom.v says so.
#
# Copyright (c) 2026 Joonatan Alanampa
# SPDX-License-Identifier: Apache-2.0
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "vendor" / "usb_hid_host_rom.hex"
DST = ROOT / "src" / "usb_hid_rom.svh"

# The upstream module declares `reg [3:0] mem [0:535]`. Hard-coded rather than
# derived from the file so a SHORT hex file is an error here instead of a ROM
# that is quietly half x — the same failure this whole file exists to prevent.
WORDS = 536


def main():
    words = []
    for line in SRC.read_text().split():
        tok = line.strip()
        if not tok or tok.startswith("//"):
            continue
        words.append(int(tok, 16) & 0xF)

    if len(words) != WORDS:
        raise SystemExit(
            f"{SRC} has {len(words)} nibbles, expected {WORDS}. The vendored "
            "core's ROM is a fixed size; a mismatch means the copy is not the "
            "version usb_hid_host.v was written against.")

    out = [
        "// usb_hid_rom.svh — GENERATED by tools/mkusbrom.py, do not edit.",
        "// Microcode for vendor/usb_hid_host.v, from vendor/usb_hid_host_rom.hex.",
        "// An include rather than a $readmemh so the path resolves the same from",
        "// the repo root (yosys) and from test/ (the simulators) — see the script.",
        f"    // {WORDS} nibbles",
        "    initial begin",
    ]
    for i, w in enumerate(words):
        out.append(f"        mem[{i}] = 4'h{w:x};")
    out.append("    end")
    DST.write_text("\n".join(out) + "\n")
    print(f"{DST.relative_to(ROOT)}: {WORDS} nibbles")


if __name__ == "__main__":
    main()
