/// sta-blackbox
//
// DFFRF_2R1W — behavioural model of the AUCOHL/DFFRAM 32x32 2R1W register-file
// macro (design name DFFRF_2R1W, generated by `dffram.py -s 32x32 -b ::rf -v
// 2R1W`). This file is the SYNTHESIS/SIM stand-in for the hard macro:
//   * `/// sta-blackbox` tells Yosys/OpenSTA to treat it as a black box during
//     synthesis — the real timing/area come from the vendored .lib/.lef, and the
//     real gates from macros/DFFRF_2R1W.nl.v (see src/config.json MACROS).
//   * The body below is a faithful RTL model of the macro's function so that
//     gate-level / behavioural simulation of the whole SoC is meaningful.
//
// READ TIMING (the fact that matters): the macro is COMBINATIONAL-READ /
// synchronous-write. DA/DB reflect the currently-stored word for RA/RB the
// same instant (through the internal decoders + RFWORD read muxes); only writes
// are clocked. Contrast src/regfile.sv, which is REGISTERED-read (sync, one
// cycle, read-first). regfile.sv's USE_MACRO wrapper bridges the two by
// registering THIS macro's output (see the wrapper for the equivalence proof).
//
// R0_ZERO=1: word 0 has no storage (RFWORD0) and always reads 0; writes to
// RW==0 are discarded. Matches regfile.sv forcing x0 to 0.
//
// Provenance + license: macros/README.txt (Apache-2.0, AUCOHL/DFFRAM).

`default_nettype none

module DFFRF_2R1W (
`ifdef USE_POWER_PINS
    input  wire         VPWR,
    input  wire         VGND,
`endif
    input  wire         CLK,
    input  wire         WE,
    input  wire [4:0]   RA,     // read port A address
    input  wire [4:0]   RB,     // read port B address
    input  wire [4:0]   RW,     // write address
    input  wire [31:0]  DW,     // write data
    output wire [31:0]  DA,     // read port A data (combinational)
    output wire [31:0]  DB      // read port B data (combinational)
);
    reg [31:0] regs [0:31];

    // synchronous write; word 0 is not stored (R0_ZERO=1)
    always @(posedge CLK)
        if (WE && RW != 5'd0)
            regs[RW] <= DW;

    // combinational read; word 0 reads as zero
    assign DA = (RA == 5'd0) ? 32'd0 : regs[RA];
    assign DB = (RB == 5'd0) ? 32'd0 : regs[RB];
endmodule

`default_nettype wire
